2024-11-06 16:37:14.985 | INFO     | __main__:main:15 - 正在初始化机器人...
2024-11-06 16:37:14.987 | INFO     | src.robot.flexiv:__init__:22 - 正在连接Flexiv机器人 192.168.2.110...
2024-11-06 16:37:15.590 | INFO     | src.robot.flexiv:__init__:26 - 正在使能机器人...
2024-11-06 16:37:15.616 | INFO     | src.robot.flexiv:__init__:28 - 机器人初始化完成
2024-11-06 16:37:15.616 | INFO     | __main__:main:22 - 正在初始化相机...
2024-11-06 16:37:16.151 | INFO     | __main__:main:29 - 正在初始化标记检测器...
2024-11-06 16:37:16.155 | INFO     | __main__:main:36 - 正在初始化手眼标定器...
2024-11-06 16:37:16.158 | INFO     | src.calibration.hand_eye_calibrator:__init__:36 - 手眼标定器初始化完成，使用eye_in_hand方法
2024-11-06 16:37:16.161 | ERROR    | __main__:main:74 - 程序运行出错: Error in call to target 'src.calibration.data_collector.CalibrationDataCollector':
TypeError("__init__() got an unexpected keyword argument 'save_images'")
full_key: collector
2024-11-06 16:37:16.161 | ERROR    | __main__:main:75 - 
2024-11-06 16:37:16.170 | INFO     | __main__:main:78 - 程序已终止
